/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedicalApplication;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

//This class edits and sends the email

public class EditMailFrame extends javax.swing.JFrame {

    /**
     * Creates new form SendMailFrame
     * @throws java.io.FileNotFoundException
     */
    
    
    public EditMailFrame() throws FileNotFoundException, IOException {

    initComponents();

    try {
        BufferedReader reader = new BufferedReader(new FileReader(System.getProperty("user.dir") + "/src/data/SendData.txt"));

        String StudentName = reader.readLine();
        String StudentGradeIndex = reader.readLine();
        String ExemptedFrom = reader.readLine();
        String ExemptedTo = reader.readLine();
        String Comments = reader.readLine();

        reader.close();

        File ExcelFile = new File(System.getProperty("user.dir") + "/src/data/teachers.xlsx");
        FileInputStream FIS = new FileInputStream(ExcelFile);
        BufferedInputStream BIS = new BufferedInputStream(FIS);

        //Get the workbook instance for XLS file
        XSSFWorkbook Workbook = new XSSFWorkbook(BIS);

        //Get first sheet from the workbook
        XSSFSheet sheet = Workbook.getSheetAt(0);
        XSSFRow row = sheet.getRow(Integer.valueOf(StudentGradeIndex) + 1);

        Iterator < Cell > cellIterator = row.cellIterator();
        //Iterate through each rows from first sheet

        String StudentGrade = cellIterator.next().getStringCellValue();
        String TeacherName = cellIterator.next().getStringCellValue();
        String TeacherEmail1 = cellIterator.next().getStringCellValue();
        String TeacherEmail2 = cellIterator.next().getStringCellValue();

        TeacherNameField.setText(TeacherName);
        TeacherEmailArea.setText(TeacherEmail1 + "\n" + TeacherEmail2);
        SubjectField.setText("Exemption of " + StudentName);
        BodyArea.setText("Dear " + TeacherName + "," + "\n" + StudentName + " from " + StudentGrade + " is exempted from lessons of Physical Eduction from " + ExemptedFrom + " to " + ExemptedTo + "\n" + Comments + "\n" + "Medical department of Skolkovo Gymnasium");

        Workbook.close();
        FIS.close();
        BIS.close();
        BufferedWriter writer = new BufferedWriter(new FileWriter(System.getProperty("user.dir") + "/src/data/SendData.txt"));
        writer.close();

    } catch (IOException e) {}


}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TeacherName = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Subject = new javax.swing.JLabel();
        Body = new javax.swing.JLabel();
        TeacherNameField = new javax.swing.JTextField();
        SubjectField = new javax.swing.JTextField();
        BodyScrollPane = new javax.swing.JScrollPane();
        BodyArea = new javax.swing.JTextArea();
        SendButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        TeacherEmailPane = new javax.swing.JScrollPane();
        TeacherEmailArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        TeacherName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TeacherName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TeacherName.setText("Name of the teacher:");
        jPanel1.add(TeacherName);
        TeacherName.setBounds(130, 40, 120, 20);

        Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Email.setText("Email:");
        jPanel1.add(Email);
        Email.setBounds(190, 70, 60, 20);

        Subject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Subject.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Subject.setText("Subject:");
        jPanel1.add(Subject);
        Subject.setBounds(180, 150, 70, 20);

        Body.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Body.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Body.setText("Body:");
        jPanel1.add(Body);
        Body.setBounds(190, 180, 60, 20);

        TeacherNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(TeacherNameField);
        TeacherNameField.setBounds(260, 40, 250, 20);
        jPanel1.add(SubjectField);
        SubjectField.setBounds(260, 150, 250, 20);

        BodyArea.setColumns(20);
        BodyArea.setRows(5);
        BodyArea.setText("\n");
        BodyScrollPane.setViewportView(BodyArea);

        jPanel1.add(BodyScrollPane);
        BodyScrollPane.setBounds(260, 180, 350, 130);

        SendButton.setText("Send");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SendButton);
        SendButton.setBounds(260, 320, 140, 40);

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(10, 30, 90, 40);

        TeacherEmailArea.setColumns(20);
        TeacherEmailArea.setRows(5);
        TeacherEmailPane.setViewportView(TeacherEmailArea);

        jPanel1.add(TeacherEmailPane);
        TeacherEmailPane.setBounds(260, 70, 250, 76);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //This method sends the letter via email
    
    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        try {
    String[] lines = TeacherEmailArea.getText().split("\\n");

    String Email = TeacherEmailArea.getText();
    String Subject = SubjectField.getText();
    String Message = BodyArea.getText();


    BufferedReader reader = new BufferedReader(new FileReader(System.getProperty("user.dir") + "/src/data/Email.txt"));
    String User = reader.readLine();
    String Password = reader.readLine();

    reader.close();

    for (int j = 0; j < lines.length; j++) {
        SendMail.send(lines[j], Subject, Message, User, Password);
    }
} catch (IOException e) {}
                
    }//GEN-LAST:event_SendButtonActionPerformed

    //This method returns the user back to AddStudentFrame
    
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void TeacherNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherNameFieldActionPerformed
    }//GEN-LAST:event_TeacherNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new EditMailFrame().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(EditMailFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Body;
    private javax.swing.JTextArea BodyArea;
    private javax.swing.JScrollPane BodyScrollPane;
    private javax.swing.JLabel Email;
    private javax.swing.JButton SendButton;
    private javax.swing.JLabel Subject;
    private javax.swing.JTextField SubjectField;
    private javax.swing.JTextArea TeacherEmailArea;
    private javax.swing.JScrollPane TeacherEmailPane;
    private javax.swing.JLabel TeacherName;
    private javax.swing.JTextField TeacherNameField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
