/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedicalApplication;

import java.awt.Desktop;
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

//This mclass edits email and password of the user and imports the database of grades, corresponding PE teachers and their emails

public class SettingsFrame extends javax.swing.JFrame {

    /**
     * Creates new form SecondFrame
     */
    
    public SettingsFrame() {
        
        initComponents();
        
        try {
            try (BufferedReader reader = new BufferedReader(new FileReader(System.getProperty("user.dir") + "/src/data/Email.txt"))) {
                SenderEmailField.setText(reader.readLine());
                PasswordField.setText(reader.readLine());
            }
         }
          catch (IOException e) {
		}
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        SenderEmailField = new javax.swing.JTextField();
        SavePasswordButton = new javax.swing.JButton();
        ImportTeachersButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        Password = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        CommentaryLabel2 = new javax.swing.JLabel();
        CommentaryLabel1 = new javax.swing.JLabel();
        CommentaryLabel3 = new javax.swing.JLabel();
        CommentaryLabel4 = new javax.swing.JLabel();
        CommentaryLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Name.setText("Email:");
        jPanel1.add(Name);
        Name.setBounds(110, 110, 70, 20);
        jPanel1.add(SenderEmailField);
        SenderEmailField.setBounds(190, 110, 180, 20);

        SavePasswordButton.setText("Save changes");
        SavePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePasswordButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SavePasswordButton);
        SavePasswordButton.setBounds(190, 170, 130, 20);

        ImportTeachersButton.setText("Import Data about Teachers");
        ImportTeachersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportTeachersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ImportTeachersButton);
        ImportTeachersButton.setBounds(500, 110, 180, 40);

        BackButton.setText("back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(10, 30, 90, 40);

        Password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Password.setText("Password:");
        jPanel1.add(Password);
        Password.setBounds(110, 140, 70, 20);
        jPanel1.add(PasswordField);
        PasswordField.setBounds(190, 140, 180, 20);

        CommentaryLabel2.setText("account, from which emails are sent:");
        CommentaryLabel2.setDoubleBuffered(true);
        jPanel1.add(CommentaryLabel2);
        CommentaryLabel2.setBounds(190, 80, 210, 20);

        CommentaryLabel1.setText("Change adress and password for the email");
        CommentaryLabel1.setDoubleBuffered(true);
        jPanel1.add(CommentaryLabel1);
        CommentaryLabel1.setBounds(190, 60, 230, 20);

        CommentaryLabel3.setText("Note! To let the application send emails, you have");
        CommentaryLabel3.setDoubleBuffered(true);
        jPanel1.add(CommentaryLabel3);
        CommentaryLabel3.setBounds(160, 220, 290, 20);

        CommentaryLabel4.setText("to allow less secure apps in google account. ");
        CommentaryLabel4.setDoubleBuffered(true);
        jPanel1.add(CommentaryLabel4);
        CommentaryLabel4.setBounds(170, 240, 270, 20);

        CommentaryLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CommentaryLabel5.setText("(click here to open the link)");
        CommentaryLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CommentaryLabel5.setDoubleBuffered(true);
        CommentaryLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CommentaryLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(CommentaryLabel5);
        CommentaryLabel5.setBounds(190, 270, 170, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //This method returns the user back to MainFrame
    
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed

        dispose();
        MainFrame JFrameObj = new MainFrame();
        JFrameObj.setVisible(true);

    }//GEN-LAST:event_BackButtonActionPerformed

    //This method imports database of grades and teachers
    
    private void ImportTeachersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportTeachersButtonActionPerformed
        try {
    JFileChooser ExcelFileChooser = new JFileChooser("D:\\Mine stuff\\IA\\CS");
    ExcelFileChooser.setDialogTitle("Select Excel File");
    FileNameExtensionFilter Filter = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
    ExcelFileChooser.setFileFilter(Filter);
    int ExcelChooser = ExcelFileChooser.showOpenDialog(null);

    File ExcelFile = ExcelFileChooser.getSelectedFile();
    FileInputStream FIS = new FileInputStream(ExcelFile);
    BufferedInputStream BIS = new BufferedInputStream(FIS);

    //Get the workbook instance for XLS file
    XSSFWorkbook Workbook = new XSSFWorkbook(BIS);

    FileOutputStream FOS = new FileOutputStream(new File(System.getProperty("user.dir") + "/src/data/teachers.xlsx"));
    JOptionPane.showMessageDialog(null, "Imported Successfully");
    Workbook.write(FOS);
    FOS.close();
    FIS.close();
    BIS.close();
    Workbook.close();

} catch (FileNotFoundException e) {} catch (IOException e) {}
    }//GEN-LAST:event_ImportTeachersButtonActionPerformed

    //This method saves the email and the passord to Email.txt
    
    private void SavePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePasswordButtonActionPerformed

        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter(System.getProperty("user.dir") + "/src/data/Email.txt"));
            writer.write( SenderEmailField.getText() +"\n" + new String(PasswordField.getPassword()));
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(SettingsFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_SavePasswordButtonActionPerformed

    //This method redirects the user to a site to enable suspicious applications setting
    
    private void CommentaryLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CommentaryLabel5MouseClicked
        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
            try {
                Desktop.getDesktop().browse(new URI("https://myaccount.google.com/lesssecureapps"));
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(SettingsFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_CommentaryLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> {
            new AddStudentFrame().setVisible(true);
        });
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CommentaryLabel1;
    private javax.swing.JLabel CommentaryLabel2;
    private javax.swing.JLabel CommentaryLabel3;
    private javax.swing.JLabel CommentaryLabel4;
    private javax.swing.JLabel CommentaryLabel5;
    private javax.swing.JButton ImportTeachersButton;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton SavePasswordButton;
    private javax.swing.JTextField SenderEmailField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}









